# Generated by Django 4.1.5 on 2023-03-10 16:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('nbpermis', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(choices=[('homme', 'homme'), ('femme', 'femme')], max_length=20)),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[250, 350], upload_to='photo')),
                ('adresse', models.CharField(max_length=200)),
                ('numberPhone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('ville', models.CharField(blank=True, max_length=30, null=True)),
                ('postal', models.IntegerField(blank=True, null=True)),
                ('Nbcontrat', models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('permission', models.CharField(choices=[('Client', 'Client'), ('Commercial', 'Commercial'), ('Administrateur', 'Administrateur')], default='Client', max_length=20)),
                ('jeune', models.BooleanField(default=False)),
                ('commercial', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('plaque', models.CharField(max_length=20)),
                ('photo_voiture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[250, 350], upload_to='photo')),
                ('typee', models.CharField(choices=[('Berline', 'berline'), ('Coupée', 'Coupée'), ('Hayon', 'Hayon'), ('Pick-up', 'Pick-up'), ('Crossover', 'Crossover'), ('SUV', 'SUV'), ('Fourgonettes', 'Fourgonettes'), ('Cabriolets', 'Cabriolets'), ('Roadsters', 'Roadsters'), ('Targa', 'Targa')], max_length=20)),
                ('annee', models.DateField(blank=True, null=True)),
                ('couleur', models.CharField(choices=[('Rouge', 'Rouge'), ('Gris', 'Gris'), ('Blanche', 'Blanche'), ('Bleu', 'Bleu'), ('Noire', 'Noire'), ('Jaune', 'Jaune'), ('Verte', 'Verte'), ('Maron', 'Maron'), ('Violette', 'Violette'), ('Rose', 'Rose'), ('Beige', 'Beige'), ('Silver', 'Silver')], max_length=20)),
                ('chevaux', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage', models.CharField(max_length=20)),
                ('numberPhone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('adresse', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('plaque', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('marque', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compte.marque')),
            ],
        ),
        migrations.CreateModel(
            name='Constat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blesse', models.BooleanField(default=False)),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.DateField(blank=True, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=50, null=True)),
                ('code_postal', models.IntegerField(blank=True, null=True)),
                ('tel', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('typee', models.CharField(blank=True, choices=[('Berline', 'berline'), ('Coupée', 'Coupée'), ('Hayon', 'Hayon'), ('Pick-up', 'Pick-up'), ('Crossover', 'Crossover'), ('SUV', 'SUV'), ('Fourgonettes', 'Fourgonettes'), ('Cabriolets', 'Cabriolets'), ('Roadsters', 'Roadsters'), ('Targa', 'Targa')], max_length=20, null=True)),
                ('couleur', models.CharField(blank=True, choices=[('Rouge', 'Rouge'), ('Gris', 'Gris'), ('Blanche', 'Blanche'), ('Bleu', 'Bleu'), ('Noire', 'Noire'), ('Jaune', 'Jaune'), ('Verte', 'Verte'), ('Maron', 'Maron'), ('Violette', 'Violette'), ('Rose', 'Rose'), ('Beige', 'Beige'), ('Silver', 'Silver')], max_length=20, null=True)),
                ('plaque', models.CharField(blank=True, max_length=20, null=True)),
                ('nbpermis', models.CharField(blank=True, max_length=20, null=True)),
                ('nbcontrat', models.CharField(blank=True, max_length=20, null=True)),
                ('assurance', models.CharField(blank=True, choices=[('1', 'Assureplus'), ('2', 'Direct Assurance'), ('3', 'Eurofils'), ('4', 'MMA'), ('5', 'Active Assurance'), ('6', 'Acomme Assurance'), ('7', 'MAAF'), ('8', 'Allianz'), ('9', "L'olivier Assurance"), ('10', 'Leocare'), ('11', 'SOS Malus'), ('12', 'Lablette'), ('13', 'AXA'), ('15', 'Matmut'), ('16', 'Cardif'), ('17', 'SwissLife'), ('18', 'MAIF'), ('19', 'AMF'), ('20', 'LCL Assurance'), ('21', 'GROUPAMA'), ('22', 'April'), ('23', 'GENERAL ASSURANCE'), ('24', 'AVIVA'), ('25', 'Banque Postale'), ('26', 'Carrefour ASSURANCE'), ('27', 'AGPM')], max_length=35, null=True)),
                ('nbCirconstance', models.CharField(blank=True, max_length=2, null=True)),
                ('degatsA', models.CharField(blank=True, choices=[('1', 'dégat sur mon véhicule'), ('2', "dégat sur l'autre véhicule"), ('3', 'dégat sur véhicule autre que A et B'), ('4', 'dégat sur objet autre que A et B')], max_length=20, null=True)),
                ('degatsB', models.CharField(blank=True, choices=[('1', 'dégat sur mon véhicule'), ('2', "dégat sur l'autre véhicule"), ('3', 'dégat sur véhicule autre que A et B'), ('4', 'dégat sur objet autre que A et B')], max_length=20, null=True)),
                ('degatouA', models.CharField(blank=True, choices=[('devant', 'devant'), ('arriere', 'arriere'), ('coter droit', 'coter droit'), ('coter gauche', 'coter gauche')], max_length=20, null=True)),
                ('degatouB', models.CharField(blank=True, choices=[('devant', 'devant'), ('arriere', 'arriere'), ('coter droit', 'coter droit'), ('coter gauche', 'coter gauche')], max_length=20, null=True)),
                ('degatautre', models.BooleanField(default=False)),
                ('lieu', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse_accident', models.CharField(blank=True, max_length=50, null=True)),
                ('degat_vehicule_a', models.CharField(blank=True, max_length=50, null=True)),
                ('degat_vehicule_b', models.CharField(blank=True, max_length=50, null=True)),
                ('commentaireA', models.CharField(blank=True, max_length=200, null=True)),
                ('commentaireB', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[250, 350], upload_to='photo')),
                ('temoin', models.CharField(blank=True, max_length=50, null=True)),
                ('signature', models.BooleanField(default=False)),
                ('circonstance', models.ManyToManyField(max_length=20, to='compte.accident')),
                ('modeles', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compte.modele')),
                ('personne', models.OneToOneField(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voiture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compte.marque')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='Contrat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compte.formule'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='marque',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compte.marque'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='modeles',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compte.modele'),
        ),
    ]
