# Generated by Django 4.1.5 on 2023-03-08 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constat',
            old_name='commentaire',
            new_name='commentaireA',
        ),
        migrations.RemoveField(
            model_name='constat',
            name='dégats',
        ),
        migrations.RemoveField(
            model_name='constat',
            name='personne2',
        ),
        migrations.AddField(
            model_name='constat',
            name='blesse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='constat',
            name='code_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constat',
            name='commentaireB',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='constat',
            name='couleur',
            field=models.CharField(blank=True, choices=[('Rouge', 'Rouge'), ('Gris', 'Gris'), ('Blanche', 'Blanche'), ('Bleu', 'Bleu'), ('Noire', 'Noire'), ('Jaune', 'Jaune'), ('Verte', 'Verte'), ('Maron', 'Maron'), ('Violette', 'Violette'), ('Rose', 'Rose'), ('Beige', 'Beige'), ('Silver', 'Silver')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='constat',
            name='degatautre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='constat',
            name='degatouA',
            field=models.CharField(blank=True, choices=[('devant', 'devant'), ('arriere', 'arriere'), ('coter droit', 'coter droit'), ('coter gauche', 'coter gauche')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='constat',
            name='degatsA',
            field=models.CharField(blank=True, choices=[('1', 'dégat sur mon véhicule'), ('2', "dégat sur l'autre véhicule"), ('3', 'dégat sur véhicule autre que A et B'), ('4', 'dégat sur objet autre que A et B')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='constat',
            name='degatsB',
            field=models.CharField(blank=True, choices=[('1', 'dégat sur mon véhicule'), ('2', "dégat sur l'autre véhicule"), ('3', 'dégat sur véhicule autre que A et B'), ('4', 'dégat sur objet autre que A et B')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='constat',
            name='heure',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constat',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='constat',
            name='prenom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='constat',
            name='tel',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AddField(
            model_name='constat',
            name='typee',
            field=models.CharField(blank=True, choices=[('Berline', 'berline'), ('Coupée', 'Coupée'), ('Hayon', 'Hayon'), ('Pick-up', 'Pick-up'), ('Crossover', 'Crossover'), ('SUV', 'SUV'), ('Fourgonettes', 'Fourgonettes'), ('Cabriolets', 'Cabriolets'), ('Roadsters', 'Roadsters'), ('Targa', 'Targa')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='constat',
            name='adresse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='constat',
            name='plaque',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
