# Generated by Django 4.1.5 on 2023-03-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_constat_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='constat',
            name='temoin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
