# Generated by Django 4.1.5 on 2023-03-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_constat_temoin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constat',
            old_name='circontance',
            new_name='circonstance',
        ),
        migrations.RenameField(
            model_name='constat',
            old_name='nbCircontance',
            new_name='nbCirconstance',
        ),
    ]
