# Generated by Django 4.1.5 on 2023-03-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0005_rename_circontance_constat_circonstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constat',
            name='signature',
            field=models.BooleanField(default=False),
        ),
    ]
