# Generated by Django 4.1.5 on 2023-03-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0006_constat_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='constat',
            name='degatouB',
            field=models.CharField(blank=True, choices=[('devant', 'devant'), ('arriere', 'arriere'), ('coter droit', 'coter droit'), ('coter gauche', 'coter gauche')], max_length=20, null=True),
        ),
    ]
