# Generated by Django 4.1.5 on 2023-03-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0007_constat_degatoub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constat',
            name='heure',
        ),
        migrations.AlterField(
            model_name='constat',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
