# Generated by Django 4.1.5 on 2023-03-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0008_remove_constat_heure_alter_constat_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constat',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
