# Generated by Django 4.1.5 on 2023-03-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0009_alter_constat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constat',
            name='assurance',
            field=models.CharField(blank=True, choices=[('1', 'Assureplus'), ('2', 'Direct Assurance'), ('3', 'Eurofils'), ('4', 'MMA'), ('5', 'Active Assurance'), ('6', 'Acomme Assurance'), ('7', 'MAAF'), ('8', 'Allianz'), ('9', "L'olivier Assurance"), ('10', 'Leocare'), ('11', 'SOS Malus'), ('12', 'Lablette'), ('13', 'AXA'), ('15', 'Matmut'), ('16', 'Cardif'), ('17', 'SwissLife'), ('18', 'MAIF'), ('19', 'AMF'), ('20', 'LCL Assurance'), ('21', 'GROUPAMA'), ('22', 'April'), ('23', 'GENERAL ASSURANCE'), ('24', 'AVIVA'), ('25', 'Banque Postale'), ('26', 'Carrefour ASSURANCE'), ('27', 'AGPM')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='constat',
            name='degatautre',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
