# Generated by Django 4.1.5 on 2023-03-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0010_alter_constat_assurance_alter_constat_degatautre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constat',
            name='personne',
        ),
    ]
